const Images = {
  bar2: require("./bar.jpeg"),
  food1: require("./food1.jpg"),
  food2: require("./food2.jpeg"),
  food4: require("./food4.jpg"),
  food7: require("./food7.jpg"),
  one: require("./1.jpeg"),
  two: require("./2.jpeg"),
  three: require("./3.jpeg"),
  four: require("./4.jpeg"),
  five: require("./5.jpeg"),
  six: require("./6.jpg"),
  eight: require("./6.jpeg"),
  group: require("./group.jpg"),
  gentleman: require("./gentleman.jpg"),
  signature: require("./signature.png"),
  maholcafe: require("./Maholcafe.png"),
  back: require("./back.webp"),
  reservation2: require("./reservation2.jpg"),
};
export default Images;
